### ISSUE TITLE
Note on how to edit .gitlab-ci.yml to put an overlay for non-backward-compatible changes

### ISSUE THREAD

**Issue by erikmd** [math-comp/math-comp#293]
Following yesterday's meeting, I've taken a look at the GitLab CI doc https://docs.gitlab.com/ce/ci/yaml/ and it should be possible to slightly edit the `.gitlab-ci.yml` file (i.e. no need for separate overlay scripts) in case a PR breaks a "child CI project", to act as an overlay.

**Note:** I did not tested this on a realistic example nor automated the edition of `.gitlab-ci.yml` below, but I open this issue to document the steps, in case we want to automate this later on, if this need for overlay occurs in math-comp.

To sum up:
* assuming a math-comp PR 1234 breaks the `ci-fourcolor-dev` job
    ```yml
    ci-fourcolor-dev:
      extends: .ci-fourcolor
      variables:
        COQ_VERSION: "dev"
    ```
* assuming a non-backward-compatible, downstream patch has been pushed to a separated branch `fix-foo` in a fork `https://github.com/user/fourcolor.git`
* then one would only need to add a commit in the PR, replacing the above four lines with:
    ```yml
    ci-fourcolor-dev:
      extends: .ci-fourcolor
      variables:
        COQ_VERSION: "dev"
      # lines below have been added
      except:
        - /^pr-1234$/
        - /^github-branch$/

    ci-fourcolor-dev-1234:
      extends: .ci-fourcolor
      variables:
        COQ_VERSION: "dev"
        CONTRIB_URL: "https://github.com/user/fourcolor.git"
        CONTRIB_VERSION: "fix-foo"
      only:
        - /^pr-1234$/
        - /^github-branch$/
    ```
    where `github-branch` denotes the **name of the GitHub source branch of the PR, assuming it is part of the upstream (math-comp) repo**.  
    If the PR is opened from a math-comp **fork**, the two `- /^github-branch$/` lines should be skipped.
* so the upcoming build CI in `pr-1234` will use the specified branch, while after the merge in `master`, the regular branch of fourcolor will be used (assuming it has integrated the downstream patch).
